### ISSUE TITLE
[FEAT] 환경 세팅

### ISSUE THREAD

**Issue by kssumin** [kssumin/week13-board#1]
### ✨ Describe

프로젝트 초기 환경 세팅을 진행합니다.

### ✅ Tasks

- [x] spring 기본 환경세팅
- [x] 로컬용 db 세팅
- [x] spotless 설정
- [x] sonar cloud 설정
- [x] CI 설정
- [x] flyway 설정
- [x] open api 문서화 task 설정

### 🕰️ Estimated Time of Completion

3h
